[package]
name = "api"
version.workspace = true
edition.workspace = true

[[bin]]
name = "api"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
indexer = { path = "../indexer" }
places = { path = "../places" }
reqwest = { version = "0.12", features = ["json"] }
tantivy = "0.22"
tokio = { workspace = true }
axum = "0.7"
tower-http = { version = "0.5", features = ["cors", "fs", "compression-gzip"] }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { version = "4", features = ["derive", "env"] }
